name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: true

      - name: Install dependencies
        run: |
          cd temporal
          go mod download

      - name: Build
        run: |
          cd temporal
          go build -v ./...

      - name: Test
        run: |
          cd temporal
          go test -v ./...

      - name: Lint
        run: |
          cd temporal
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run ./...
